// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// This class provides the default [FirebaseOptions] for different platforms.
/// The options are configured based on the platform the app is running on.
class DefaultFirebaseOptions {

  // Retrieve the Firebase configuration based on the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
    // Handle unsupported platforms, such as Linux.
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32RE_Q0CF6a4tJ8IXUgq53m1Mma3P9q0',
    appId: '1:1080102377214:android:6a5a04a3b3ce75cbde37af',
    messagingSenderId: '1080102377214',
    projectId: 'proyek-akhir-9e65d',
    databaseURL: 'https://proyek-akhir-9e65d-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-akhir-9e65d.appspot.com',
  );

  // Firebase configuration for Web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32RE_Q0CF6a4tJ8IXUgq53m1Mma3P9q0',
    appId: '1:1080102377214:web:c322ef99b349ca76de37af',
    messagingSenderId: '1080102377214',
    projectId: 'proyek-akhir-9e65d',
    authDomain: 'proyek-akhir-9e65d.firebaseapp.com',
    databaseURL: 'https://proyek-akhir-9e65d-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-akhir-9e65d.appspot.com',
    measurementId: 'G-WTH2PT6XQ1',
  );

  // Firebase configuration for macOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB32RE_Q0CF6a4tJ8IXUgq53m1Mma3P9q0',
    appId: '1:1080102377214:ios:5dfe67806dca9b5dde37af',
    messagingSenderId: '1080102377214',
    projectId: 'proyek-akhir-9e65d',
    databaseURL: 'https://proyek-akhir-9e65d-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-akhir-9e65d.appspot.com',
    iosBundleId: 'com.example.flapp',
  );

  // Firebase configuration for iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB32RE_Q0CF6a4tJ8IXUgq53m1Mma3P9q0',
    appId: '1:1080102377214:ios:5dfe67806dca9b5dde37af',
    messagingSenderId: '1080102377214',
    projectId: 'proyek-akhir-9e65d',
    databaseURL: 'https://proyek-akhir-9e65d-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-akhir-9e65d.appspot.com',
    iosBundleId: 'com.example.flapp',
  );

  // Firebase configuration for Windows.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB32RE_Q0CF6a4tJ8IXUgq53m1Mma3P9q0',
    appId: '1:1080102377214:web:e4b5898b7c2c1fe6de37af',
    messagingSenderId: '1080102377214',
    projectId: 'proyek-akhir-9e65d',
    authDomain: 'proyek-akhir-9e65d.firebaseapp.com',
    databaseURL: 'https://proyek-akhir-9e65d-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-akhir-9e65d.appspot.com',
    measurementId: 'G-FF243XY13E',
  );
}
